name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  # Test:
  #   name: ${{ matrix.os }} - Pulsar
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - macos-latest
  #         - windows-latest
  #       # targets:
  #       #   - { eslint: "7", node: "12.x" }
  #       #   - { eslint: "7", node: "14.x" }
  #       #   - { eslint: "8", node: "12.x" }
  #       #   - { eslint: "8", node: "14.x" }
  #       #   - { eslint: "8", node: "16.x" }
  #       #   - { eslint: "9", node: "18.x" }
  #       #   - { eslint: "9", node: "20.x" }
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pulsar-edit/action-pulsar-dependency@v3.3
  #     - uses: volta-cli/action@v4
  #       with:
  #         node-version: ${{ matrix.targets.node }}
  #     - run: pulsar --package install
  #     - run: npx atom-package-deps .
  #     - run: pulsar --package list --enabled --packages
  #     - uses: coactions/setup-xvfb@v1
  #       with:
  #         run: pulsar --test spec

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm install
      - run: npm run test.lint

  # Release:
  #   needs: [Test, Lint]
  #   if: github.ref == 'refs/heads/main' &&
  #     github.event.repository.fork == false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pulsar-edit/action-pulsar-dependency@v3.3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "lts/*"
  #     - name: NPM install
  #       run: npm install
  #     - name: Release 🎉
  #       uses: cycjimmy/semantic-release-action@v3
  #       with:
  #         branches: |
  #           ['main']
  #         extends: |
  #           @semantic-release/apm-config
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         ATOM_ACCESS_TOKEN: ${{ secrets.ATOM_ACCESS_TOKEN  }}
